-- Chronicle Gate Online v3
-- Run once in Supabase SQL Editor, or apply with Supabase CLI migrations.

create table if not exists public.room_sessions (
  room_code text primary key check (room_code ~ '^[A-HJ-NP-Z2-9]{5}$'),
  state jsonb not null,
  revision bigint not null default 1,
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days')
);

-- Safe upgrade path for users who applied an older migration.
alter table public.room_sessions
  add column if not exists revision bigint not null default 1;

create index if not exists room_sessions_expires_at_idx
  on public.room_sessions (expires_at);

create table if not exists public.session_events (
  id bigint generated by default as identity primary key,
  room_code text not null,
  event_type text not null check (char_length(event_type) between 1 and 64),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists session_events_room_code_created_at_idx
  on public.session_events (room_code, created_at desc);

alter table public.room_sessions enable row level security;
alter table public.session_events enable row level security;

-- Browsers never query these tables. The Render server uses a Supabase secret key.
-- Secret keys map to service_role and bypass RLS; anon/authenticated get no direct access.
revoke all on table public.room_sessions from public, anon, authenticated;
revoke all on table public.session_events from public, anon, authenticated;

-- The server-side secret key resolves to service_role. Grant only the operations used by this app.
grant select on table public.room_sessions to service_role;
grant insert on table public.session_events to service_role;
grant usage, select on sequence public.session_events_id_seq to service_role;

create or replace function public.cleanup_expired_chronicle_rooms()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.room_sessions where expires_at < now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.cleanup_expired_chronicle_rooms() from public, anon, authenticated;

-- Monotonic snapshot writer. During a rolling Render deploy, an older process can
-- finish a delayed request after a newer process. This function ignores older revisions.
create or replace function public.save_chronicle_room(
  p_room_code text,
  p_state jsonb,
  p_revision bigint,
  p_expires_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.room_sessions (room_code, state, revision, updated_at, expires_at)
  values (p_room_code, p_state, p_revision, now(), p_expires_at)
  on conflict (room_code) do update
    set state = excluded.state,
        revision = excluded.revision,
        updated_at = now(),
        expires_at = excluded.expires_at
  where public.room_sessions.revision <= excluded.revision;
end;
$$;

revoke all on function public.save_chronicle_room(text, jsonb, bigint, timestamptz) from public, anon, authenticated;
grant execute on function public.save_chronicle_room(text, jsonb, bigint, timestamptz) to service_role;
